# Generated by Django 5.2.11 on 2026-03-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='pet_images')),
                ('description', models.TextField(default='No description provided.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.category')),
            ],
        ),
    ]
