# Generated by Django 5.2.11 on 2026-03-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
